### ISSUE TITLE
After Heroku Deployment Products will not save.

### ISSUE THREAD

**Issue by gndclouds** [yongfook/zipsell#13]
Had some issues with figaro, and installed ENV on heroku as dynamo. Which seamed to work out. However when I try to make a new product and save it, the product never saves. 

Any thoughts on how to determine ifs an amazon setting or heroku build issue.

Heroku console:

`
2019-02-14T04:43:35.780528+00:00 app[web.1]: I, [2019-02-14T04:43:35.780434 #4]  INFO -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] [paperclip] Trying to link /tmp/54dc05cdc8a2babf246b99ae4630012020190214-4-11n0bwn.pdf to /tmp/79e9f490298a1de6558b3d11573c2cc820190214-4-1813ie8.pdf
2019-02-14T04:43:35.780966+00:00 app[web.1]: I, [2019-02-14T04:43:35.780868 #4]  INFO -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] Command :: file -b --mime '/tmp/79e9f490298a1de6558b3d11573c2cc820190214-4-1813ie8.pdf'
2019-02-14T04:43:35.783246+00:00 app[web.1]: I, [2019-02-14T04:43:35.783151 #4]  INFO -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] [paperclip] Content Type Spoof: Filename OOAK_Object_Test_Page.pdf (inode/x-empty from Headers, ["application/pdf"] from Extension), content type discovered from file command: inode/x-empty. See documentation to allow this combination.
2019-02-14T04:43:35.788564+00:00 app[web.1]: D, [2019-02-14T04:43:35.788462 #4] DEBUG -- : [a592eb97-02c9-4a4d-beac-38649f5a5385]   [1m[35m (1.2ms)[0m  [1m[31mROLLBACK[0m
2019-02-14T04:43:35.789083+00:00 app[web.1]: I, [2019-02-14T04:43:35.788986 #4]  INFO -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] Completed 422 Unprocessable Entity in 37ms (ActiveRecord: 5.1ms)
2019-02-14T04:43:35.790057+00:00 app[web.1]: F, [2019-02-14T04:43:35.789962 #4] FATAL -- : [a592eb97-02c9-4a4d-beac-38649f5a5385]   
2019-02-14T04:43:35.790156+00:00 app[web.1]: F, [2019-02-14T04:43:35.790067 #4] FATAL -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] ActiveRecord::RecordInvalid (Validation failed: Image has contents that are not what they are reported to be, Image is invalid, File has contents that are not what they are reported to be, Image content type is invalid):
2019-02-14T04:43:35.790248+00:00 app[web.1]: F, [2019-02-14T04:43:35.790163 #4] FATAL -- : [a592eb97-02c9-4a4d-beac-38649f5a5385]   
2019-02-14T04:43:35.790369+00:00 app[web.1]: F, [2019-02-14T04:43:35.790265 #4] FATAL -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] app/controllers/products_controller.rb:32:in `block in create'
2019-02-14T04:43:35.790371+00:00 app[web.1]: [a592eb97-02c9-4a4d-beac-38649f5a5385] app/controllers/products_controller.rb:31:in `create'
`

**Comment by galliani** [comment]
> Had some issues with figaro, and installed ENV on heroku as dynamo. Which seamed to work out. However when I try to make a new product and save it, the product never saves.
> 
> Any thoughts on how to determine ifs an amazon setting or heroku build issue.
> 
> Heroku console:
> 
> `2019-02-14T04:43:35.780528+00:00 app[web.1]: I, [2019-02-14T04:43:35.780434 #4] INFO -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] [paperclip] Trying to link /tmp/54dc05cdc8a2babf246b99ae4630012020190214-4-11n0bwn.pdf to /tmp/79e9f490298a1de6558b3d11573c2cc820190214-4-1813ie8.pdf 2019-02-14T04:43:35.780966+00:00 app[web.1]: I, [2019-02-14T04:43:35.780868 #4] INFO -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] Command :: file -b --mime '/tmp/79e9f490298a1de6558b3d11573c2cc820190214-4-1813ie8.pdf' 2019-02-14T04:43:35.783246+00:00 app[web.1]: I, [2019-02-14T04:43:35.783151 #4] INFO -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] [paperclip] Content Type Spoof: Filename OOAK_Object_Test_Page.pdf (inode/x-empty from Headers, ["application/pdf"] from Extension), content type discovered from file command: inode/x-empty. See documentation to allow this combination. 2019-02-14T04:43:35.788564+00:00 app[web.1]: D, [2019-02-14T04:43:35.788462 #4] DEBUG -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] �[1m�[35m (1.2ms)�[0m �[1m�[31mROLLBACK�[0m 2019-02-14T04:43:35.789083+00:00 app[web.1]: I, [2019-02-14T04:43:35.788986 #4] INFO -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] Completed 422 Unprocessable Entity in 37ms (ActiveRecord: 5.1ms) 2019-02-14T04:43:35.790057+00:00 app[web.1]: F, [2019-02-14T04:43:35.789962 #4] FATAL -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] 2019-02-14T04:43:35.790156+00:00 app[web.1]: F, [2019-02-14T04:43:35.790067 #4] FATAL -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] ActiveRecord::RecordInvalid (Validation failed: Image has contents that are not what they are reported to be, Image is invalid, File has contents that are not what they are reported to be, Image content type is invalid): 2019-02-14T04:43:35.790248+00:00 app[web.1]: F, [2019-02-14T04:43:35.790163 #4] FATAL -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] 2019-02-14T04:43:35.790369+00:00 app[web.1]: F, [2019-02-14T04:43:35.790265 #4] FATAL -- : [a592eb97-02c9-4a4d-beac-38649f5a5385] app/controllers/products_controller.rb:32:in`block in create'
> 2019-02-14T04:43:35.790371+00:00 app[web.1]: [a592eb97-02c9-4a4d-beac-38649f5a5385] app/controllers/products_controller.rb:31:in `create' `

This is the one causing problem:

> ActiveRecord::RecordInvalid (Validation failed: Image has contents that are not what they are reported to be, Image is invalid, File has contents that are not what they are reported to be, Image content type is invalid)

This is because the image type you uploaded is considered invalid, hence AR rolled back your submission.
